name: LOGICS-original
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - rdkit
  - tensorflow=1.15
  - keras=2.3.1
  - fcd
  - h5py=2.10.0
  - pytorch=1.11.0 
  - torchvision=0.12.0
  - torchaudio=0.11.0
  - cudatoolkit=11.3
  - pandas
  - MulticoreTSNE
  - scikit-learn=1.0.2
  - seaborn
  - ipykernel